[platformio]
src_dir = src

[env:native-doctest]
platform = native
build_flags = -std=gnu++17 -g -O0
    -I src
    -I src/embedded_trace
    -DDOCTEST_CONFIG_SUPER_FAST_ASSERTS
build_src_filter =
    +<embedded_trace/>
    +<embedded_trace_esp32/>
test_build_src = yes
test_filter = test_native
lib_deps = doctest/doctest@^2.4.11
